### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by Tylerjet**
update automation.md to include file watching service, also make on-boot service more distinguished as klipper-backup-on-boot.service instead of klipper-backup.service

### CODE REVIEW

**Comment by Tylerjet** [comment]
Making as a draft cause of course now the image doesn't want to be in the correct spot

**Comment by Staubgeborener** [comment]
I love the commit messages

**Comment by Tomblarom** [comment]
Unfortunately I'm running into issues with the inotify service:
```
pi@rpi3-3d-ender:~ $ sudo systemctl status klipper-backup-filewatch.service
● klipper-backup-filewatch.service - Klipper Backup Filewatch Service
   Loaded: loaded (/etc/systemd/system/klipper-backup-filewatch.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

Feb 25 12:38:16 rpi3-3d-ender systemd[1]: klipper-backup-filewatch.service: Succeeded.
Feb 25 12:38:49 rpi3-3d-ender systemd[1]: Started Klipper Backup Filewatch Service.
Feb 25 12:38:49 rpi3-3d-ender bash[987]: inotifywait: invalid option -- 'P'
Feb 25 12:38:49 rpi3-3d-ender systemd[1]: klipper-backup-filewatch.service: Succeeded.

```

**Comment by Tomblarom** [comment]
Additionally the script could be altered to fed the `exclude` list from `.env` into `exclude_pattern` as well. 😉

**Comment by Staubgeborener** [comment]
This script is using the newest inotify version (version > 4), see [this](https://github.com/Staubgeborener/klipper-backup/issues/63#issuecomment-1951540043) post.

**Pull request merged**
