### PR TITLE
Fixes Issue #6 , Improvements, Changes, Added Feature

### PR DESCRIPTION
**Pull request by Tylerjet**
- Removed Install.sh and version file - No longer needed
- Updated README.md with instructions for install
- Added checks to script.sh to not backup read-only symbolic-linked files (Fluidd.cfg, Mainsail.cfg, KAMP, etc..) , and only backup the main printer.cfg
- Other various changes to script.sh for more efficiency and simplicity
- FEATURE ADD: allow for user defined commit user.name and user.email for commit messages to backup repo.
- FIXES: Issue #6, Backup folder is now outside of the main repository which ensures that the repo is not seen as dirty by moonraker

This does have breaking changes due to the new paths used for folder and files, see .env.example for new structure to follow

### CODE REVIEW

**Comment by Staubgeborener** [comment]
I merged the code for testing into the [dev branch](https://github.com/Staubgeborener/klipper-backup/tree/dev). Is this code working on your side? 

Running the `script.sh` for the first time leads to this output
```shell
Skipping symbolic link: /home/pi/printer_data/config/KAMP
Skipping symbolic link: /home/pi/printer_data/config/mainsail.cfg
Skipping file: /home/pi/printer_data/config/printer-20230528_174042.cfg
Skipping file: /home/pi/printer_data/config/printer-20230720_133952.cfg
Skipping file: /home/pi/printer_data/config/printer-20230720_135620.cfg
Skipping file: /home/pi/printer_data/config/printer-20230720_140934.cfg
Skipping symbolic link: /home/pi/printer_data/config/timelapse.cfg
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /home/pi/config_backup/.git/
New backup from 10-01-24
[master (root-commit) 1d4eade] New backup from 10-01-24
 15 files changed, 1718 insertions(+)
 create mode 100644 README.md
 create mode 100644 klipper/GET_PROBE_LIMITS.cfg
 create mode 100644 klipper/adxl.cfg
 create mode 100644 klipper/crowsnest.conf
 create mode 100644 klipper/macros.cfg
 create mode 100644 klipper/moonraker.conf
 create mode 100644 klipper/pa_cal.cfg
 create mode 100644 klipper/pa_flow_calibrate.cfg
 create mode 100644 klipper/printer.cfg
 create mode 100644 klipper/saved_variables.cfg
 create mode 100644 klipper/secrets.conf
 create mode 100644 klipper/shell_command.cfg
 create mode 100644 klipper/sonar.conf
 create mode 100644 klipper/sounds.cfg
 create mode 100644 klipper/telegram.conf
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/Staubgeborener/klipper-backup-test-dev.git'
```

Running it a second time:
```shell
Skipping symbolic link: /home/pi/printer_data/config/KAMP
Skipping symbolic link: /home/pi/printer_data/config/mainsail.cfg
Skipping file: /home/pi/printer_data/config/printer-20230528_174042.cfg
Skipping file: /home/pi/printer_data/config/printer-20230720_133952.cfg
Skipping file: /home/pi/printer_data/config/printer-20230720_135620.cfg
Skipping file: /home/pi/printer_data/config/printer-20230720_140934.cfg
Skipping symbolic link: /home/pi/printer_data/config/timelapse.cfg
New backup from 10-01-24
On branch master
nothing to commit, working tree clean
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/Staubgeborener/klipper-backup-test-dev.git'
```

And truly, there is no new push in [my backup GitHub repository](https://github.com/Staubgeborener/klipper-backup-test-dev).
So in the end I had to handle this error
```shell
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/Staubgeborener/klipper-backup-test-dev.git'
```
I added `git branch -M main` after `git config init.defaultBranch main` to get rid of it. After running `script.sh` again, I get a successful push in my backup GitHub repository.

**Comment by Staubgeborener** [comment]
So far, I tested the following:
- [x] script can be updated via moonraker update manager
- [x] successfully push new backup into repository
- [x] individual username in `.env` works as expected 
- [ ] test backup functionality with different setups (different files, different folders, include/exclude files and folders via `.env` etc)
- [ ] check possibility for users to easily migrate to `v 1.0` without breaking everything

**Review by Staubgeborener — CHANGES_REQUESTED** [review]
Add this at the beginning of the `script.sh` so we can check for new updates via shell:

```shell
# Check for updates
[ $(git rev-parse HEAD) = $(git ls-remote $(git rev-parse --abbrev-ref @{u} | \
sed 's/\// /g') | cut -f1) ] && echo -e "Klipper-backup is up to date\n" || echo -e "Klipper-backup is $(tput setaf 1)not$(tput sgr0) up to date, consider making a $(tput setaf 1)git pull$(tput sgr0) to update\n"
```

Add this after `git config init.defaultBranch main` in order to get rid of error messages:
```shell
git branch -M main
```

**Comment by Tylerjet** [comment]
> I merged the code for testing into the [dev branch](https://github.com/Staubgeborener/klipper-backup/tree/dev). Is this code working on your side?
> 
> Running the `script.sh` for the first time leads to this output
> 
> ```shell
> Skipping symbolic link: /home/pi/printer_data/config/KAMP
> Skipping symbolic link: /home/pi/printer_data/config/mainsail.cfg
> Skipping file: /home/pi/printer_data/config/printer-20230528_174042.cfg
> Skipping file: /home/pi/printer_data/config/printer-20230720_133952.cfg
> Skipping file: /home/pi/printer_data/config/printer-20230720_135620.cfg
> Skipping file: /home/pi/printer_data/config/printer-20230720_140934.cfg
> Skipping symbolic link: /home/pi/printer_data/config/timelapse.cfg
> hint: Using 'master' as the name for the initial branch. This default branch name
> hint: is subject to change. To configure the initial branch name to use in all
> hint: of your new repositories, which will suppress this warning, call:
> hint:
> hint:   git config --global init.defaultBranch <name>
> hint:
> hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
> hint: 'development'. The just-created branch can be renamed via this command:
> hint:
> hint:   git branch -m <name>
> Initialized empty Git repository in /home/pi/config_backup/.git/
> New backup from 10-01-24
> [master (root-commit) 1d4eade] New backup from 10-01-24
>  15 files changed, 1718 insertions(+)
>  create mode 100644 README.md
>  create mode 100644 klipper/GET_PROBE_LIMITS.cfg
>  create mode 100644 klipper/adxl.cfg
>  create mode 100644 klipper/crowsnest.conf
>  create mode 100644 klipper/macros.cfg
>  create mode 100644 klipper/moonraker.conf
>  create mode 100644 klipper/pa_cal.cfg
>  create mode 100644 klipper/pa_flow_calibrate.cfg
>  create mode 100644 klipper/printer.cfg
>  create mode 100644 klipper/saved_variables.cfg
>  create mode 100644 klipper/secrets.conf
>  create mode 100644 klipper/shell_command.cfg
>  create mode 100644 klipper/sonar.conf
>  create mode 100644 klipper/sounds.cfg
>  create mode 100644 klipper/telegram.conf
> error: src refspec main does not match any
> error: failed to push some refs to 'https://github.com/Staubgeborener/klipper-backup-test-dev.git'
> ```
> 
> Running it a second time:
> 
> ```shell
> Skipping symbolic link: /home/pi/printer_data/config/KAMP
> Skipping symbolic link: /home/pi/printer_data/config/mainsail.cfg
> Skipping file: /home/pi/printer_data/config/printer-20230528_174042.cfg
> Skipping file: /home/pi/printer_data/config/printer-20230720_133952.cfg
> Skipping file: /home/pi/printer_data/config/printer-20230720_135620.cfg
> Skipping file: /home/pi/printer_data/config/printer-20230720_140934.cfg
> Skipping symbolic link: /home/pi/printer_data/config/timelapse.cfg
> New backup from 10-01-24
> On branch master
> nothing to commit, working tree clean
> error: src refspec main does not match any
> error: failed to push some refs to 'https://github.com/Staubgeborener/klipper-backup-test-dev.git'
> ```
> 
> And truly, there is no new push in [my backup GitHub repository](https://github.com/Staubgeborener/klipper-backup-test-dev). So in the end I had to handle this error
> 
> ```shell
>  Using 'master' as the name for the initial branch. This default branch name
> [...]
> error: src refspec main does not match any
> error: failed to push some refs to 'https://github.com/Staubgeborener/klipper-backup-test-dev.git'
> ```
> 
> I added `git branch -M main` after `git config init.defaultBranch main` to get rid of it ([example](https://github.com/Staubgeborener/klipper-backup/commit/22d07e12693f29552fc10152aaed28b87b44c30d#diff-116b4e2bac3e35befdfae3f3b6eb88911689c30bfe6696d9e6b0139da8cb5e72R53)). After running `script.sh` again, I get a successful push in my backup GitHub repository.

Was the script ran in a folder that already was initialized? as yes that code all ran fine from a fresh repo and folder, I do now realize an oversight on my behalf, right now the script is under the impression that the folder either does not have the .git folder (so no initialized repo, or that they are following the soon to be new standard of using a main branch instead of master as the default.

I'll look at a way to add a check to find the branch they are on or create the main branch if its a first time install.

**Comment by Tylerjet** [comment]
slight edit to the above need to look into the default branch as was able to reproduce by pulling any reference to defaultBranch in global and system git config settings for some reason git is not following the config command just after init like it should be

**Comment by Staubgeborener** [comment]
? Your edit is not in this PR

**Comment by Tylerjet** [comment]
> ? Your edit is not in this PR

whoops meant edit to the above comment

**Comment by Tylerjet** [comment]
Alright adjusted the README.md, as well added that update check to the beginning and my modifications for the repository branch are in there as well, improved it a bit more so that you can now set the name of the branch if a user does not want main they can change it. As well as grabbing the branch name if .git already exists.

**Comment by Staubgeborener** [comment]
Just let me know as soon as you're done with the commits and your work

**Comment by Tylerjet** [comment]
@Staubgeborener That should be it for those changes.

**Review by Staubgeborener — APPROVED** [review]

**Pull request merged**
